### PR TITLE
BetterC document.

### PR DESCRIPTION
**Pull request by TurkeyMan**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
PR to amend the text you disagree with. I just want to get the state of the conversation recorded, since it seems contentious.

**Comment by TurkeyMan** [comment]
I'm also gonna say that, unless someone else decides to spend a reasonable amount of time on this, I'm gonna keep writing the code the way I have been ;) .. I have no motivation to write code that I can't use in my own projects.

It's not strictly betterC, it's just not making unnecessary use of Phobos, and not backing into a corner that it needs to be completely rewritten.

If there's a single API you're unhappy with because it supports betterC, can you point it out?

**Comment by p0nce** [comment]
Well, no.  I change mind very often.

**Comment by drug007** [comment]
So you will be interested in the result?

**Comment by p0nce** [comment]
From the very beginning I thought that no, (because I'm not a fan of collegial anything) but I've written what I need here https://github.com/DlangGraphicsWG/documents/wiki/What-will-make-YOU-actually-use-reject-the-image-library%3F if it improves measurably the performance of my products without much integration headache, why not use it?

**Pull request merged**
