### PR TITLE
3 different proposals, please vote separately!

### PR DESCRIPTION
**Pull request by p0nce**
In this PR I'll try to make the following points.

## (A) Images are 2D array-like objects

  **Pros:**     
Easier and intuitive, 2D is what we think when we think of an "image"
Less complexity and template work.
  **Cons:**
Some images really are 3D or more, in various scientific fields.

I'll argue that we should start with 2D because it seems possible to change this after, and in the mean time it's less work. I don't have a good grasp on what the downsides would be.

##  (B) Images (and Image operations) are range-like objects that can be composed like in `ae.utils.graphics`

Really two proposals, UFCS and compile-time interface.

As seen in https://blog.thecybershadow.net/2014/03/21/functional-image-processing-in-d/

  **Pros:**     
      Friendly and efficient UFCS chains of operations (need good names).
      The Pros of Input ranges, but for images.
  **Cons:**
      UFCS chains may leave no room to pass a complex context.
      Most of algorithms end up being written for contiguous in-memory images anyway.
      Like `std.range`, functions are all defined externally hence not quite easy to discover.

I think this is a good way to showcase DbI, i've been building on Vladimir's work this way.
The only downside I seen over the years is that such design creates more value when your pixel formats are different that RGBA8, and you change what you do with image often. It can be template-heavy at times. Sometimes I wish I only had RGBA8 images, then I remember the same algorithm can work with 16bits 1-channel images.

##  (C) Images types should have a runtime interface

  **Pros:**     
      The main advantage is that you can avoid to template something by the Image type.
      (Like std.allocator have IAllocator so that containers can avoid being templated by the allocators specific type)
      Allows crossing binary interfaces like shared libraries.
      Format conversion may need this internally.
      This "type-punning" reduce template bloat and compile times.
      Widgets that own a RGBA8 image member can be the same type as Widget that own a RGBA16 image.

  **Cons:**
      More complexity.
      The runtime interface has virtual dispatch.

Please vote with a comment A => yes/no  B => yes/no   C => yes/no

### CODE REVIEW

**Comment by igor84** [comment]
A - no
B - yes
C - yes

I understand and like how B and C sound "on paper" but I think it is something only practice can show how really good it is and I haven't really worked with that kind of API to make any claims. "A" uses some wording that makes it a bit too open to interpretation. When you say object are you specifically thinking of classes? I would then rather say struct. Also I wouldn't say images are 2D like structs, but be specific and say something like: images contain the array of bytes that represents pixels, some meta data about those pixels and provide an interface to access them as 2D array (or something like that).

**Comment by p0nce** [comment]
About (A), the main debate is whether our Image abstraction is 2-dimensional (addressed in x and y) or N-dimensional (allow any number of dimension).

Previous work of a N-dimensional range-like struct is mir's NDSlice. http://docs.algorithm.dlang.io/latest/mir_ndslice.html(a bit extreme since in this case even the dimension number is a runtime value it seems).

It doesn't say at all whether they are classes or struct, whether they own their data, it's all about resolving this 2D vs ND.

I don't have a strong opinion about it.


> I understand and like how B and C sound "on paper" but I think it is something only practice can show how really good it is and I haven't really worked with that kind of API to make any claims

Yes but when our plan will fail in the face of reality it's important to have a way to create agreement with what needs to be done :) 

It's expected that things will not go as planned, however in the workgroup I think everyone has already written UI toolkits, image libraries, and/or windowing libraries so it's not like the domain is completely unknown.

**Comment by drug007** [comment]
A. I believe that image should be ND range. At least 1D, 2D and 3D ones should be available.
B. yes
C. yes

**Comment by ahmetsait** [comment]
A => no ~ish. I would say at least 3D should be there if not ND.
B => no ~ish. Not because I'm against the idea but rather I feel like in order to make it play nicely in a GUI toolkit it shouldn't heavily rely on templates.
C=> yes ~ I think we can make image modifiers templated and let image to be a runtime type so it doesn't have to be entirely no-template all the way down.

**Comment by drug007** [comment]
@ahmetsait  but `B` do not force image to be templated all the way day. You always can wrap templated image so the wrapper would be non templated image. Also I don't think that a gui toolkit shouldn't be templated, but this is other issue.

**Comment by ahmetsait** [comment]
@drug007 Fair enough. Maybe I should scratch some code to understand how it would turn out.

**Comment by p0nce** [comment]
B => ACCEPTED (3 votes "yes", 1 vote "no")
C => ACCEPTED (4 votes "yes", 0 vote "no")

So according to process they can be merged.

I think @ahmetsait makes very valid criticism of B and we should be on the lookout for problems with templates.

Essentially the trade-off is "Concrete image and operations on images are the same thing. " vs "Images are anything that follow the runtime interface", essentially it's static polymorphism vs dynamic dispatch.

We've said we would try to have both with an `IAllocator`-like thing but we don't know yet (`IImage` ?) how practical it is.
Here is how IAllocator is implemented from a static interface: https://github.com/dlang-community/stdx-allocator/blob/60715a7c81db33ee0cc365670d213213628c827a/source/stdx/allocator/package.d#L2164

I'll readily admit going static polymorphism is partly to make D shine, however making D shine is not necessarily the top priority. Let's be ready to backpedal if this fails.

**Comment by drug007** [comment]
@ahmetsait I agree. We definitely should test our ideas. For me the good example of image is [ae.utils.graphics.image](https://github.com/CyberShadow/ae/blob/master/utils/graphics/image.d), also [ggplotd](https://github.com/BlackEdder/ggplotd) seems interesting - this is example of declarative way.

**Pull request merged**
