### PR TITLE
Images being 2D proposal, number 2

### PR DESCRIPTION
**Pull request by p0nce**
This proposal makes the case that Image should be 2D.

Please vote to show your care for the topic 🗳️

### CODE REVIEW

**Comment by drug007** [comment]
Now I think that low level image should be 2D.

**Comment by TurkeyMan** [comment]
I'd consider a future expansion of the definition, where an image may be 2d arrays.
That would allow for images to be ie; associated sets, cube maps, animations, 3d depth planes (3d images), etc.
But let's not for now.

**Comment by p0nce** [comment]
@TurkeyMan "sets of image" may include multi-planar images, that are especially annoying to deal with. Complicated matter!

**Comment by p0nce** [comment]
Rebased!

**Pull request merged**
